### ISSUE TITLE
AX88U support 

### ISSUE THREAD

**Issue by ilker-aktuna** [MartineauUK/Quota-Monitor#1]
Does this work on newer models like AX88U with firmware 386 ?

**Comment by MartineauUK** [comment]
Although there appears to be an issue if you are using '-' hyphen characters in the hostnames of your LAN devices, the script only uses standard iptable commands so should work on firmware v386.

**Comment by ilker-aktuna** [comment]
on my router (AX88U) it can not find the function "ExpandIPRange"
I do not see this function defined in the script. Where is it ?

**Comment by MartineauUK** [comment]
http://www.snbforums.com/threads/per-ip-traffic-accounting.74582/post-713199

So if file '/jffs/configs/IPGroups' exists (as it always has on my routers) then there is no need for the ExpandIPRange() function.

However, I have now added it today in v1.07 of the script.

**Comment by ilker-aktuna** [comment]
ok. it still does not work on this router. (AX88U)

```
admin@RT-AX88U-26C8:/jffs/scripts# ./QuotaMonitor.sh resetdel

 v1.07 Quota Monitoring.....

        Quota Monitoring does not exist.

admin@RT-AX88U-26C8:/jffs/scripts# ./QuotaMonitor.sh monitor init ip=192.168.254.20

 v1.07 Quota Monitoring.....

        Quota Monitoring Setup complete.


        ***ERROR '192.168.254.20' already in monitor list or (192.168.254.20) invalid?
Monitoring Resuming in 00:01:00 seconds....q^C
```

**Comment by MartineauUK** [comment]
Can you please enter the following debugging commands and post the output

./QuotaMonitor.sh   resetdel
modprobe   xt_comment
sh   -x   ./QuotaMonitor.sh   init   ip=192.168.254.20
./QuotaMonitor.sh   status

**Comment by ilker-aktuna** [comment]
I think I found the problem.
2 issues actually:
1. "Wan: Use local caching DNS server as system resolver" was not set to "yes" , so it prevents reverse dns lookup for LAN hosts
2. There are hosts that do not have a name registered. 

Both issues are solved by removing the DNS lookup in your script.

**Comment by MartineauUK** [comment]
I have uploaded v1.08 that allows monitoring of LAN devices that do not have a registered hostname. Many thanks!

**Comment by ilker-aktuna** [comment]
thanks. actually I solved it on mine by adding a fake hostname in format HOST192168254001
it now works fine for me.

**Comment by ilker-aktuna** [comment]
I start monitoring withh your script and then check the output with following commands:
iptables  -vL MyQUOTAi  
iptables  -vL MyQUOTAo

these show the packet count and bytes for input and output per device.
However, I made a simple test and the collected information seems wrong.
I reset counters, download a 3GB file and then check the command output.
I do not run QuotaMonitor in monitor mode while doing this test.

The output shown for the device which downloaded 3GB is about 1.7MB 
it is about 1/2000 of the actual downloaded data.

So what might be the problem here causing this difference ?
